#! /bin/sh

PROGRAM=`basename $0`

##################### .JS/bin/_SH_UTIL_FUNCTIONS <BEGIN> #######################
EVAL()
{
    echo "#!CMD:[" $@ "]"
    eval "$@"
}

NEWFILE()
{
    FILE=$1; [ -z "$FILE" ] && { echo 1>&2 "($PROGRAM:NEWFILE)Error: FILE is not set"; exit 100;}

    REAL_FILE=.$FILE/`date "+%Y%m%d-%H%M%S"`#$FILE

    mkdir -p .$FILE || exit 101
    if [ -h $FILE ]; then
rm -f $FILE
    elif [ -e $FILE ]; then
echo 1>&2 "($PROGRAM:NEWFILE)Note: '$FILE' exists and is not a symbolic file. Renamed to '$REAL_FILE.bak'"
        mv $FILE $REAL_FILE.bak
    fi
touch $REAL_FILE && ln -s $REAL_FILE $FILE && echo $REAL_FILE || exit 102
}
##################### .JS/bin/_SH_UTIL_FUNCTIONS <END> #########################
usage()
{
    echo 1>&2 "Usage: $PROGRAM -i TESTPLAN -d APACHE_DIR"
    echo 1>&2 " $PROGRAM -i TS -d AJC121207"
}

b=18
B=100
SLEEP=60

while [ $# -gt 0 ]; do
    case "$1" in
        -b) shift; b="$1";;
        -B) shift; B="$1";;
        --sleep) shift; SLEEP="$1";;
        --help) usage; exit 0;;
        *) echo 1>&2 "($PROGRAM)Error: Invalid option '$1'"; usage; exit 1;;
    esac
shift
done

{
    for I in 1 2 3 4; do
        EVAL doc.manage.py query -t $I -b $b -B $B
        sleep $SLEEP
        EVAL doc.manage.py download -t $I -b $b -B $B
        sleep $SLEEP
        EVAL doc.manage.py query --no_verify -t $I -b $b -B $B
        sleep $SLEEP
        echo
    done

    for I in 6 8 10 12 14 16; do
        EVAL doc.manage.py query -t $I -b $b -B $B
        sleep $SLEEP
        EVAL doc.manage.py query --no_verify -t $I -b $b -B $B
        sleep $SLEEP
        echo
    done
} 2>&1 | tee `NEWFILE $PROGRAM.log`
